In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

# Customers Dataset

In [2]:
customer_file_name = r'../data/raw/olist_customers_dataset.csv'
df_customer = pd.read_csv(customer_file_name)
df_customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [3]:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [4]:
print("length of dataframe: ",len(df_customer))
for column in df_customer.columns:
    print(f"total unique values in {column}: ",df_customer[column].nunique())

length of dataframe:  99441
total unique values in customer_id:  99441
total unique values in customer_unique_id:  96096
total unique values in customer_zip_code_prefix:  14994
total unique values in customer_city:  4119
total unique values in customer_state:  27

# Geolocation Dataset

In [5]:
df_geo = pd.read_csv(r'../data/raw/olist_geolocation_dataset.csv')
df_geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [6]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [7]:
print("length of dataframe: ",len(df_geo))
for column in df_geo.columns:
    print(f"total unique values in {column}: ",df_geo[column].nunique())

length of dataframe:  1000163
total unique values in geolocation_zip_code_prefix:  19015
total unique values in geolocation_lat:  717360
total unique values in geolocation_lng:  717613
total unique values in geolocation_city:  8011
total unique values in geolocation_state:  27

# Orders dataset

In [8]:
df_orders = pd.read_csv(r'../data/raw/olist_orders_dataset.csv')
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [9]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [50]:
#Checking order_ids overlap between orders and customer dataset
set(df_orders['customer_id'].unique())-set(df_customer['customer_id'].unique()),\
set(df_customer['customer_id'].unique())-set(df_orders['customer_id'].unique())

(set(), set())

In [10]:
df_orders['order_delivered_customer_date'] = pd.to_datetime(df_orders['order_delivered_customer_date'])
df_orders['order_delivered_customer_date_only'] = df_orders['order_delivered_customer_date'].dt.normalize()
df_orders['order_estimated_delivery_date'] = pd.to_datetime(df_orders['order_estimated_delivery_date'])
df_orders['delay'] = (df_orders['order_delivered_customer_date_only'] - df_orders['order_estimated_delivery_date']).dt.days

In [11]:
df_orders.describe()

,order_delivered_customer_date,order_estimated_delivery_date,order_delivered_customer_date_only,delay
count,96476,99441,96476,96476.000000
mean,2018-01-14 12:09:19.035542272,2018-01-24 03:08:37.730111232,2018-01-13 19:24:32.449106432,-11.876881
min,2016-10-11 13:46:32,2016-09-30 00:00:00,2016-10-11 00:00:00,-147.000000
25%,2017-09-25 22:07:22.249999872,2017-10-03 00:00:00,2017-09-25 00:00:00,-17.000000
50%,2018-02-02 19:28:10.500000,2018-02-15 00:00:00,2018-02-02 00:00:00,-12.000000
75%,2018-05-15 22:48:52.249999872,2018-05-25 00:00:00,2018-05-15 00:00:00,-7.000000
max,2018-10-17 13:22:46,2018-11-12 00:00:00,2018-10-17 00:00:00,188.000000
std,NaN,NaN,NaN,10.183854

In [12]:
print("length of dataframe: ",len(df_orders))
for column in df_orders.columns:
    print(f"total unique values in {column}: ",df_orders[column].nunique())

length of dataframe:  99441
total unique values in order_id:  99441
total unique values in customer_id:  99441
total unique values in order_status:  8
total unique values in order_purchase_timestamp:  98875
total unique values in order_approved_at:  90733
total unique values in order_delivered_carrier_date:  81018
total unique values in order_delivered_customer_date:  95664
total unique values in order_estimated_delivery_date:  459
total unique values in order_delivered_customer_date_only:  645
total unique values in delay:  198

In [13]:
df_orders['order_status'].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [43]:
df_orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [14]:
df_orders['order_status'].value_counts(normalize=True)*100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

# Order items dataset

In [15]:
df_items = pd.read_csv(r'../data/raw/olist_order_items_dataset.csv')
df_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [16]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [17]:
df_items['cost'] = df_items['price']+df_items['freight_value']

In [18]:
print("length of dataframe: ",len(df_items))
for column in df_items.columns:
    print(f"total unique values in {column}: ",df_items[column].nunique())

length of dataframe:  112650
total unique values in order_id:  98666
total unique values in order_item_id:  21
total unique values in product_id:  32951
total unique values in seller_id:  3095
total unique values in shipping_limit_date:  93318
total unique values in price:  5968
total unique values in freight_value:  6999
total unique values in cost:  29149

In [52]:
#checking overlap between order ids in orders vs items dataset
len(set(df_orders['order_id'].unique())-set(df_items['order_id'].unique())),\
len(set(df_items['order_id'].unique())-set(df_orders['order_id'].unique()))

(775, 0)

###### Only 555 out of 1298 days data is present

In [19]:
df_items.describe()

       order_item_id          price  freight_value           cost
count  112650.000000  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320     140.644059
std         0.705124     183.633928      15.806405     190.724394
min         1.000000       0.850000       0.000000       6.080000
25%         1.000000      39.900000      13.080000      55.220000
50%         1.000000      74.990000      16.260000      92.320000
75%         1.000000     134.900000      21.150000     157.937500
max        21.000000    6735.000000     409.680000    6929.310000

In [20]:
#joining order_items with orders dataset to get delivery status
print(len(df_orders),len(df_items))
df_items_orders = df_items.merge(df_orders,on='order_id',how='left')
print(len(df_items_orders))
df_items_orders.head()

99441 112650
112650

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,cost,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_delivered_customer_date_only,delay
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,2017-09-20,-9.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,2017-05-12,-3.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,2018-01-22,-14.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,2018-08-14,-6.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,2017-03-01,-16.0

In [37]:

order_summary = df_items_orders.groupby(['order_id','order_status']).agg(products_per_order=("product_id","count"),
                                               unique_products_per_order = ("product_id","nunique"),
                                               order_price = ("price","sum"),
                                               order_freight = ("freight_value","sum"),
                                               order_cost = ('cost',"sum")).reset_index()
order_summary[['products_per_order','unique_products_per_order','order_price','order_freight','order_cost']].mean()

products_per_order             1.141731
unique_products_per_order      1.038098
order_price                  137.754076
order_freight                 22.823562
order_cost                   160.577638
dtype: float64

In [41]:
status_summary = order_summary.groupby('order_status')\
    [['products_per_order','unique_products_per_order','order_price','order_freight','order_cost']].mean()
status_summary

,products_per_order,unique_products_per_order,order_price,order_freight,order_cost
order_status,,,,,
approved,1.500000,1.000000,104.800000,15.740000,120.540000
canceled,1.175705,1.008677,206.584100,23.102928,229.687028
delivered,1.142198,1.038537,137.041586,22.785253,159.826839
invoiced,1.150641,1.032051,197.199904,23.917885,221.117788
processing,1.186047,1.016611,200.794751,29.750465,230.545216
shipped,1.071429,1.018987,136.281591,23.871519,160.153110
unavailable,1.166667,1.166667,334.615000,22.133333,356.748333

In [53]:
df_shipped_delivered

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,cost,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_delivered_customer_date_only,delay
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,2017-09-20,-9.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,2017-05-12,-3.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,2018-01-22,-14.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,2018-08-14,-6.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,2017-03-01,-16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,2018-05-10,-8.0
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,2018-07-23,-9.0
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,2017-11-10,2017-10-28,-13.0
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40,2017-08-25,2017-08-16,-9.0
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,2018-06-14,-14.0

In [44]:
df_shipped_delivered = df_items_orders[df_items_orders['order_status'].isin(['delivered','shipped'])]

df_product_stats = df_shipped_delivered.groupby("product_id").agg(total_quantity=("product_id","count"),
                                                     total_price = ("price","sum"),
                                                     total_freight = ("freight_value","sum"),
                                                     total_cost = ("cost","sum"))
#Top Products contributing to 80% of orders
df_top_80_orders_qty = df_product_stats.sort_values(by='total_quantity',ascending=False)
df_top_80_orders_qty['cum_qty'] = df_top_80_orders_qty['total_quantity'].cumsum()
df_top_80_orders_qty['cum_pct'] = df_top_80_orders_qty['cum_qty']/df_top_80_orders_qty['total_quantity'].sum()
df_top_80_orders_qty = df_top_80_orders_qty[df_top_80_orders_qty['cum_pct']<=0.8]
print("Total number of products contributing to 80% of orders quantity: ",len(df_top_80_orders_qty))
df_top_80_orders_qty.head()

Total number of products contributing to 80% of orders quantity:  12387

,total_quantity,total_price,total_freight,total_cost,cum_qty,cum_pct
product_id,,,,,,
aca2eb7d00ea1a7b8ebd4e68314663af,527,37608.90,7211.86,44820.76,527,0.004731
99a4788cb24856965c36a24e339b6058,486,42848.76,8008.68,50857.44,1013,0.009095
422879e10f46682990de24d770e7f83d,484,26577.22,7624.04,34201.26,1497,0.013440
389d119b48cf3043d311335e499d9c6b,391,21390.69,7224.49,28615.18,1888,0.016951
368c6c730842d78016ad823897a372db,388,21056.80,6927.60,27984.40,2276,0.020434

In [45]:
#Top Products contributing to 80% of total cost
df_top_80_orders_cost = df_product_stats.sort_values(by='total_cost',ascending=False)
df_top_80_orders_cost['cum_cost'] = df_top_80_orders_cost['total_cost'].cumsum()
df_top_80_orders_cost['cum_pct'] = df_top_80_orders_cost['cum_cost']/df_top_80_orders_cost['total_cost'].sum()
df_top_80_orders_cost = df_top_80_orders_cost[df_top_80_orders_cost['cum_pct']<=0.8]
print("Total number of products contributing to 80% of cost: ",len(df_top_80_orders_cost))
df_top_80_orders_cost.head()

Total number of products contributing to 80% of cost:  9091

,total_quantity,total_price,total_freight,total_cost,cum_cost,cum_pct
product_id,,,,,,
bb50f2e236e5eea0100680137654686c,195,63885.00,3721.10,67606.10,67606.10,0.004335
d1c427060a0f73f6b889a5c7c61f2ac4,341,46916.51,13680.78,60597.29,128203.39,0.008220
6cdd53843498f92890544667809f1595,156,54730.20,4363.79,59093.99,187297.38,0.012009
99a4788cb24856965c36a24e339b6058,486,42848.76,8008.68,50857.44,238154.82,0.015269
d6160fb7873f184099d9bc95e30376af,34,47249.35,1393.42,48642.77,286797.59,0.018388

In [54]:
print(len(df_customer),len(df_shipped_delivered))
df_shipped_delivered = df_shipped_delivered.merge(df_customer,on='customer_id',how='left')
print(len(df_shipped_delivered))

99441 111382
111382

In [57]:
orders_per_customer = df_shipped_delivered.groupby('customer_unique_id').size()
cust_orders = orders_per_customer.sort_values(ascending=False)
cust_share = cust_orders / cust_orders.sum()
cust_cum_share = cust_share.cumsum()
cust_cum_share[cust_cum_share <= 0.8]

customer_unique_id
c8460e4251689ba205045f3ea17884a1    0.000215
4546caea018ad8c692964e3382debd19    0.000404
698e1cf81d01a3d389d96145f7fa6df8    0.000584
c402f431464c72e27330a67f7b94d4fb    0.000763
0f5ac8d5c31de21d2f25e24be15bbffb    0.000925
                                      ...
c352fe3e97b9dba9794e6386e0c01b2a    0.799959
c351fc20bfae0e5f5ed16c91d3bdad68    0.799968
c351aa4c227fbb44856d1941fd50f359    0.799977
c35101ebb38317f41ffd9936ceaf8e09    0.799986
c3510151fa915096c984929abdec3805    0.799995
Length: 72121, dtype: float64