In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

# 1. Customers Dataset

In [2]:
df_customers = pd.read_csv(r'../data/raw/olist_customers_dataset.csv')
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [3]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [4]:
print("length of dataframe: ",len(df_customers))
for column in df_customers.columns:
    print(f"total unique values in {column}: ",df_customers[column].nunique())

length of dataframe:  99441
total unique values in customer_id:  99441
total unique values in customer_unique_id:  96096
total unique values in customer_zip_code_prefix:  14994
total unique values in customer_city:  4119
total unique values in customer_state:  27

In [5]:
number_of_repeat_users = df_customers['customer_id'].nunique()-df_customers['customer_unique_id'].nunique()
print("number of reapeat users: ",number_of_repeat_users)
print("percentage of repeat users: ",number_of_repeat_users*100/df_customers['customer_unique_id'].nunique(),"%")

number of reapeat users:  3345
percentage of repeat users:  3.480894105894106 %

# 2. Geolocation Dataset

In [6]:
df_geo = pd.read_csv(r'../data/raw/olist_geolocation_dataset.csv')
df_geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [7]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [8]:
print("length of dataframe: ",len(df_geo))
for column in df_geo.columns:
    print(f"total unique values in {column}: ",df_geo[column].nunique())

length of dataframe:  1000163
total unique values in geolocation_zip_code_prefix:  19015
total unique values in geolocation_lat:  717360
total unique values in geolocation_lng:  717613
total unique values in geolocation_city:  8011
total unique values in geolocation_state:  27

In [9]:
print(len(set(df_customers['customer_zip_code_prefix'].unique())-set(df_geo['geolocation_zip_code_prefix'].unique())))
print(len(set(df_geo['geolocation_zip_code_prefix'].unique())-set(df_customers['customer_zip_code_prefix'].unique())))

157
4178

In [10]:
missing_from_geo = set(df_customers['customer_zip_code_prefix'].unique())-set(df_geo['geolocation_zip_code_prefix'].unique())
len(df_customers[df_customers['customer_zip_code_prefix'].isin(missing_from_geo)])

278

# 3. Orders dataset

In [11]:
df_orders = pd.read_csv(r'../data/raw/olist_orders_dataset.csv')
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [12]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [13]:
#Checking order_ids overlap between orders and customer dataset
set(df_orders['customer_id'].unique())-set(df_customers['customer_id'].unique()),\
set(df_customers['customer_id'].unique())-set(df_orders['customer_id'].unique())

(set(), set())

In [14]:
df_orders['order_purchase_timestamp'] = pd.to_datetime(df_orders['order_purchase_timestamp'])
df_orders['order_delivered_customer_date'] = pd.to_datetime(df_orders['order_delivered_customer_date'])
df_orders['order_estimated_delivery_date'] = pd.to_datetime(df_orders['order_estimated_delivery_date'])

df_orders['order_delivered_customer_date_only'] = df_orders['order_delivered_customer_date'].dt.normalize()
df_orders['order_estimated_delivery_date'] = df_orders['order_estimated_delivery_date'].dt.normalize()
df_orders['delay'] = (df_orders['order_delivered_customer_date_only'] - df_orders['order_estimated_delivery_date']).dt.days

In [15]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_delivered_customer_date_only,delay
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017-10-10,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018-08-07,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018-08-17,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017-12-02,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018-02-16,-10.0

In [16]:
df_orders.describe()

,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,order_delivered_customer_date_only,delay
count,99441,96476,99441,96476,96476.000000
mean,2017-12-31 08:43:12.776581120,2018-01-14 12:09:19.035542272,2018-01-24 03:08:37.730111232,2018-01-13 19:24:32.449106432,-11.876881
min,2016-09-04 21:15:19,2016-10-11 13:46:32,2016-09-30 00:00:00,2016-10-11 00:00:00,-147.000000
25%,2017-09-12 14:46:19,2017-09-25 22:07:22.249999872,2017-10-03 00:00:00,2017-09-25 00:00:00,-17.000000
50%,2018-01-18 23:04:36,2018-02-02 19:28:10.500000,2018-02-15 00:00:00,2018-02-02 00:00:00,-12.000000
75%,2018-05-04 15:42:16,2018-05-15 22:48:52.249999872,2018-05-25 00:00:00,2018-05-15 00:00:00,-7.000000
max,2018-10-17 17:30:18,2018-10-17 13:22:46,2018-11-12 00:00:00,2018-10-17 00:00:00,188.000000
std,NaN,NaN,NaN,NaN,10.183854

In [17]:
print("length of dataframe: ",len(df_orders))
for column in df_orders.columns:
    print(f"total unique values in {column}: ",df_orders[column].nunique())

length of dataframe:  99441
total unique values in order_id:  99441
total unique values in customer_id:  99441
total unique values in order_status:  8
total unique values in order_purchase_timestamp:  98875
total unique values in order_approved_at:  90733
total unique values in order_delivered_carrier_date:  81018
total unique values in order_delivered_customer_date:  95664
total unique values in order_estimated_delivery_date:  459
total unique values in order_delivered_customer_date_only:  645
total unique values in delay:  198

In [18]:
df_orders['order_status'].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [19]:
df_orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [20]:
df_orders['order_status'].value_counts(normalize=True)*100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [22]:
delivery_delay = df_orders[df_orders['order_status']=='delivered']['delay'].dropna()
print("Delivered orders with delay info: ",len(delivery_delay))
print("Early delivery: ",(delivery_delay<0).sum(), delivery_delay[delivery_delay<0].mean(), 100*(delivery_delay<0).mean(),"%")
print("Ontime delivery: ",(delivery_delay==0).sum(), delivery_delay[delivery_delay==0].mean(), 100*(delivery_delay==0).mean(),"%")
print("Ontime delivery: ",(delivery_delay>0).sum(), delivery_delay[delivery_delay>0].mean(), 100*(delivery_delay>0).mean(),"%")

Delivered orders with delay info:  96470
Early delivery:  88644 -13.707177022697532 91.88763346117965 %
Ontime delivery:  1292 0.0 1.3392764590027988 %
Ontime delivery:  6534 10.620140801958984 6.7730900798175595 %

# 4. Order items dataset

In [23]:
df_items = pd.read_csv(r'../data/raw/olist_order_items_dataset.csv')
df_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [24]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [25]:
df_items['cost'] = df_items['price']+df_items['freight_value']

In [26]:
print("length of dataframe: ",len(df_items))
for column in df_items.columns:
    print(f"total unique values in {column}: ",df_items[column].nunique())

length of dataframe:  112650
total unique values in order_id:  98666
total unique values in order_item_id:  21
total unique values in product_id:  32951
total unique values in seller_id:  3095
total unique values in shipping_limit_date:  93318
total unique values in price:  5968
total unique values in freight_value:  6999
total unique values in cost:  29149

In [27]:
#checking overlap between order ids in orders vs items dataset
len(set(df_orders['order_id'].unique())-set(df_items['order_id'].unique())),\
len(set(df_items['order_id'].unique())-set(df_orders['order_id'].unique()))

(775, 0)

In [28]:
#Trying to see if there's any pattern in this missing 775 order_id
missing_orders = list(set(df_orders['order_id'].unique())-set(df_items['order_id'].unique()))
print("orders with no items: ",len(missing_orders))
status_of_missing = df_orders[df_orders['order_id'].isin(missing_orders)]['order_status'].value_counts()
print("delivery status of breakdown of missing orders: \n",status_of_missing)
print("Missing items in delivered orders: ",len(df_orders[(df_orders['order_id'].isin(missing_orders))&\
    (df_orders['order_status']=='delivered')]))

orders with no items:  775
delivery status of breakdown of missing orders:
 order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64
Missing items in delivered orders:  0

In [29]:
df_items.describe()

       order_item_id          price  freight_value           cost
count  112650.000000  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320     140.644059
std         0.705124     183.633928      15.806405     190.724394
min         1.000000       0.850000       0.000000       6.080000
25%         1.000000      39.900000      13.080000      55.220000
50%         1.000000      74.990000      16.260000      92.320000
75%         1.000000     134.900000      21.150000     157.937500
max        21.000000    6735.000000     409.680000    6929.310000

In [30]:
#joining order_items with orders dataset to get delivery status
print(len(df_orders),len(df_items))
df_items_orders = df_items.merge(df_orders,on='order_id',how='left')
print(len(df_items_orders))
df_items_orders.head()

99441 112650
112650

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,cost,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_delivered_customer_date_only,delay
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,2017-09-20,-9.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,2017-05-12,-3.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,2018-01-22,-14.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,2018-08-14,-6.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,2017-03-01,-16.0

In [31]:

order_summary = df_items_orders.groupby(['order_id','order_status']).agg(products_per_order=("product_id","count"),
                                               unique_products_per_order = ("product_id","nunique"),
                                               order_price = ("price","sum"),
                                               order_freight = ("freight_value","sum"),
                                               order_cost = ('cost',"sum")).reset_index()
order_summary[['products_per_order','unique_products_per_order','order_price','order_freight','order_cost']].mean()

products_per_order             1.141731
unique_products_per_order      1.038098
order_price                  137.754076
order_freight                 22.823562
order_cost                   160.577638
dtype: float64

In [32]:
status_summary = order_summary.groupby('order_status')\
    [['products_per_order','unique_products_per_order','order_price','order_freight','order_cost']].mean()
status_summary

,products_per_order,unique_products_per_order,order_price,order_freight,order_cost
order_status,,,,,
approved,1.500000,1.000000,104.800000,15.740000,120.540000
canceled,1.175705,1.008677,206.584100,23.102928,229.687028
delivered,1.142198,1.038537,137.041586,22.785253,159.826839
invoiced,1.150641,1.032051,197.199904,23.917885,221.117788
processing,1.186047,1.016611,200.794751,29.750465,230.545216
shipped,1.071429,1.018987,136.281591,23.871519,160.153110
unavailable,1.166667,1.166667,334.615000,22.133333,356.748333

In [33]:
df_delivered = df_items_orders[df_items_orders['order_status'].isin(['delivered'])]

df_product_stats = df_delivered.groupby("product_id").agg(total_quantity=("product_id","count"),
                                                     total_price = ("price","sum"),
                                                     total_freight = ("freight_value","sum"),
                                                     total_cost = ("cost","sum"))
#Top Products contributing to 80% of orders
df_top_80_orders_qty = df_product_stats.sort_values(by='total_quantity',ascending=False)
df_top_80_orders_qty['cum_qty'] = df_top_80_orders_qty['total_quantity'].cumsum()
df_top_80_orders_qty['cum_pct'] = df_top_80_orders_qty['cum_qty']/df_top_80_orders_qty['total_quantity'].sum()
df_top_80_orders_qty = df_top_80_orders_qty[df_top_80_orders_qty['cum_pct']<=0.8]
print("Total number of products contributing to 80% of orders quantity: ",len(df_top_80_orders_qty),"out of: ",len(df_product_stats),
      "ratio: ",len(df_top_80_orders_qty)/len(df_product_stats))
df_top_80_orders_qty.head()

Total number of products contributing to 80% of orders quantity:  12338 out of:  32216 ratio:  0.3829774025329029

,total_quantity,total_price,total_freight,total_cost,cum_qty,cum_pct
product_id,,,,,,
aca2eb7d00ea1a7b8ebd4e68314663af,520,37104.30,7093.45,44197.75,520,0.004719
422879e10f46682990de24d770e7f83d,484,26577.22,7624.04,34201.26,1004,0.009111
99a4788cb24856965c36a24e339b6058,477,42049.66,7857.84,49907.50,1481,0.013440
389d119b48cf3043d311335e499d9c6b,390,21336.79,7206.86,28543.65,1871,0.016979
368c6c730842d78016ad823897a372db,388,21056.80,6927.60,27984.40,2259,0.020500

In [34]:
#Top Products contributing to 80% of total cost
df_top_80_orders_cost = df_product_stats.sort_values(by='total_cost',ascending=False)
df_top_80_orders_cost['cum_cost'] = df_top_80_orders_cost['total_cost'].cumsum()
df_top_80_orders_cost['cum_pct'] = df_top_80_orders_cost['cum_cost']/df_top_80_orders_cost['total_cost'].sum()
df_top_80_orders_cost = df_top_80_orders_cost[df_top_80_orders_cost['cum_pct']<=0.8]
print("Total number of products contributing to 80% of cost: ",len(df_top_80_orders_cost),"out of: ",len(df_product_stats),
      "ratio: ",len(df_top_80_orders_cost)/len(df_product_stats))
df_top_80_orders_cost.head()

Total number of products contributing to 80% of cost:  9052 out of:  32216 ratio:  0.2809783958281599

,total_quantity,total_price,total_freight,total_cost,cum_cost,cum_pct
product_id,,,,,,
bb50f2e236e5eea0100680137654686c,194,63560.00,3698.03,67258.03,67258.03,0.004362
d1c427060a0f73f6b889a5c7c61f2ac4,332,45620.56,13336.75,58957.31,126215.34,0.008185
6cdd53843498f92890544667809f1595,153,53652.30,4281.43,57933.73,184149.07,0.011942
99a4788cb24856965c36a24e339b6058,477,42049.66,7857.84,49907.50,234056.57,0.015179
3dd2a17168ec895c781a9191c1e95ad7,272,40782.80,7093.26,47876.06,281932.63,0.018284

In [35]:
print(len(df_customers),len(df_delivered))
df_delivered = df_delivered.merge(df_customers,on='customer_id',how='left')
print(len(df_delivered))

99441 110197
110197

In [36]:
df_delivered.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,cost,customer_id,order_status,...,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_delivered_customer_date_only,delay,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,3ce436f183e68e07877b285a838db11a,delivered,...,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,2017-09-20,-9.0,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,f6dd3ec061db4e3987629fe6b26e5cce,delivered,...,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,2017-05-12,-3.0,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,...,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,2018-01-22,-14.0,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,d4eb9395c8c0431ee92fce09860c5a06,delivered,...,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,2018-08-14,-6.0,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,58dbd0b2d70206bf40e62cd34e84d795,delivered,...,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,2017-03-01,-16.0,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP

In [38]:
df_unique_customer_order_pair = df_delivered[['customer_unique_id','order_id']].drop_duplicates()
orders_per_customer = df_unique_customer_order_pair.groupby('customer_unique_id')['order_id'].count()
cust_orders = orders_per_customer.sort_values(ascending=False)
(cust_orders==1).mean()

np.float64(0.9699972150217443)

In [42]:
df_unique_customer_order_pair = df_delivered[['customer_unique_id','order_id']].drop_duplicates()
orders_per_customer = df_unique_customer_order_pair.groupby('customer_unique_id')['order_id'].count()
cust_orders = orders_per_customer.sort_values(ascending=False)
print("customers with exactly one order: ",(cust_orders==1).sum(),100*(cust_orders==1).mean(),"%")
cust_share = cust_orders / cust_orders.sum()
cust_cum_share = cust_share.cumsum()
print("total customers with contributing to 80% of orders: ",(cust_cum_share<=0.8).sum(),100*(cust_cum_share<=0.8).mean(),"%")
print("total orders: ",(cust_cum_share).count())

customers with exactly one order:  90557 96.99972150217442 %
total customers with contributing to 80% of orders:  74062 79.3311767604276 %
total orders:  93358

# 5. Products Dataset

In [44]:
df_products = pd.read_csv(r'../data/raw/olist_products_dataset.csv')
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [45]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [46]:
print("length of dataframe: ",len(df_products))
for column in df_products.columns:
    print(f"total unique values in {column}: ",df_products[column].nunique())

length of dataframe:  32951
total unique values in product_id:  32951
total unique values in product_category_name:  73
total unique values in product_name_lenght:  66
total unique values in product_description_lenght:  2960
total unique values in product_photos_qty:  19
total unique values in product_weight_g:  2204
total unique values in product_length_cm:  99
total unique values in product_height_cm:  102
total unique values in product_width_cm:  95

In [47]:
df_products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [55]:
total_products = set(df_products['product_id'].unique())
purchased_products = set(df_items['product_id'].unique())
print("dissimilar products: ",len(total_products-purchased_products),len(purchased_products-total_products))
no_category_products = set(df_products[df_products['product_category_name'].isna()]['product_id'].unique())
print("total products with no category: ",len(no_category_products),100*len(no_category_products)/len(total_products),"%")
print("total no category product rows in items dataset: ",len(df_items[df_items['product_id'].isin(no_category_products)]),"out of: ",\
     len(df_items))

dissimilar products:  0 0
total products with no category:  610 1.8512336499650996 %
total no category product rows in items dataset:  1603 out of:  112650

# 6. Product Category Dataset

In [56]:
df_product_category = pd.read_csv(r'../data/raw/product_category_name_translation.csv')
df_product_category.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [57]:
df_product_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [58]:
print("length of dataframe: ",len(df_product_category))
for column in df_product_category.columns:
    print(f"total unique values in {column}: ",df_product_category[column].nunique())

length of dataframe:  71
total unique values in product_category_name:  71
total unique values in product_category_name_english:  71

In [59]:
print(len(set(df_product_category['product_category_name'].unique())-set(df_products['product_category_name'].unique())))
print(len(set(df_products['product_category_name'].unique())-set(df_product_category['product_category_name'].unique())))

0
3

In [60]:
missing_categories = list(set(df_products['product_category_name'].unique())-set(df_product_category['product_category_name'].unique()))
df_products[df_products['product_category_name'].isin(missing_categories)]['product_category_name'].unique()

array([nan, 'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'],
      dtype=object)

In [61]:
#merging english names into products
print(len(df_products),len(df_product_category))
df_products = df_products.merge(df_product_category,on='product_category_name',how='left')
print(len(df_products))

32951 71
32951

# 7. Sellers Dataset

In [62]:
df_sellers = pd.read_csv(r'../data/raw/olist_sellers_dataset.csv')
df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [63]:
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [64]:
print("length of dataframe: ",len(df_sellers))
for column in df_sellers.columns:
    print(f"total unique values in {column}: ",df_sellers[column].nunique())

length of dataframe:  3095
total unique values in seller_id:  3095
total unique values in seller_zip_code_prefix:  2246
total unique values in seller_city:  611
total unique values in seller_state:  23

In [65]:
print(set(df_sellers['seller_id'].unique())-set(df_items['seller_id'].unique()))
print(set(df_items['seller_id'].unique())-set(df_sellers['seller_id'].unique()))

set()
set()

In [69]:
seller_stats = df_delivered.groupby('seller_id').agg(
    total_items_sold = ("order_item_id","count"),
    unique_products_sold = ("product_id","nunique"),
    unique_orders = ("order_id","nunique")
).sort_values(by = 'total_items_sold',ascending=False)
seller_stats.head()

,total_items_sold,unique_products_sold,unique_orders
seller_id,,,
6560211a19b47992c3666cc44a7e94c0,1996,254,1819
4a3ca9315b744ce9f8e9374361493884,1949,394,1772
1f50f920176fa81dab994f9023523100,1926,23,1399
cc419e0650a3c5ba77189a1882b7556a,1719,37,1651
da8622b14eb17ae2831f4ac5b9dab84a,1548,221,1311

In [70]:
seller_stats.describe()

       total_items_sold  unique_products_sold  unique_orders
count       2970.000000           2970.000000    2970.000000
mean          37.103367             11.332997      32.935690
std          119.672968             24.532721     105.407111
min            1.000000              1.000000       1.000000
25%            2.000000              2.000000       2.000000
50%            8.000000              4.000000       7.000000
75%           26.000000             10.000000      22.000000
max         1996.000000            394.000000    1819.000000

# 8. Payments Dataset

In [71]:
df_payments = pd.read_csv(r'../data/raw/olist_order_payments_dataset.csv')
df_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [72]:
df_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [73]:
print("length of dataframe: ",len(df_payments))
for column in df_payments.columns:
    print(f"total unique values in {column}: ",df_payments[column].nunique())

length of dataframe:  103886
total unique values in order_id:  99440
total unique values in payment_sequential:  29
total unique values in payment_type:  5
total unique values in payment_installments:  24
total unique values in payment_value:  29077

In [81]:
df_payments['payment_sequential'].value_counts(normalize=True)*100

payment_sequential
1     95.643301
2      2.925322
3      0.559267
4      0.267601
5      0.163641
6      0.113586
7      0.078933
8      0.051980
9      0.041392
10     0.032728
11     0.027915
12     0.020214
13     0.012514
14     0.009626
15     0.007701
17     0.005776
19     0.005776
18     0.005776
16     0.005776
20     0.003850
21     0.003850
22     0.002888
24     0.001925
25     0.001925
26     0.001925
23     0.001925
27     0.000963
28     0.000963
29     0.000963
Name: proportion, dtype: float64

In [74]:
print(set(df_payments['order_id'].unique())-set(df_orders['order_id'].unique()))
print(set(df_items['order_id'].unique())-set(df_payments['order_id'].unique()))
print(set(df_orders['order_id'].unique())-set(df_payments['order_id'].unique()))
print(len(set(df_payments['order_id'].unique())-set(df_items['order_id'].unique())))

set()
{'bfbd0f9bdef84302105ad712db648a6c'}
{'bfbd0f9bdef84302105ad712db648a6c'}
775

In [75]:
df_payments.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [76]:
df_payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [77]:
df_payments['payment_type'].value_counts(normalize=True)*100

payment_type
credit_card    73.922376
boleto         19.043952
voucher         5.558978
debit_card      1.471806
not_defined     0.002888
Name: proportion, dtype: float64

In [82]:
df_multipay = df_payments[df_payments['payment_sequential']>1]
df_multipay['payment_type'].value_counts(normalize=True)*100

payment_type
voucher        91.780822
credit_card     7.048166
debit_card      1.148917
boleto          0.022095
Name: proportion, dtype: float64

In [79]:
df_payments['payment_installments'].value_counts(normalize=True)*100

payment_installments
1     50.580444
2     11.948675
3     10.069692
4      6.832489
10     5.128699
5      5.043028
8      4.108350
6      3.773367
7      1.565177
9      0.619910
12     0.128025
15     0.071232
18     0.025990
11     0.022140
24     0.017327
20     0.016364
13     0.015401
14     0.014439
17     0.007701
16     0.004813
21     0.002888
0      0.001925
22     0.000963
23     0.000963
Name: proportion, dtype: float64

In [80]:
df_credit_card = df_payments[df_payments['payment_type']=='credit_card']
df_credit_card['payment_installments'].value_counts(normalize=True)*100

payment_installments
1     33.146689
2     16.163813
3     13.621981
4      9.242789
10     6.937952
5      6.822059
8      5.557653
6      5.104499
7      2.117325
9      0.838596
12     0.173188
15     0.096360
18     0.035159
11     0.029950
24     0.023439
20     0.022137
13     0.020835
14     0.019533
17     0.010417
16     0.006511
21     0.003907
0      0.002604
22     0.001302
23     0.001302
Name: proportion, dtype: float64

# 9. Reviews Dataset

In [83]:
df_reviews = pd.read_csv(r'../data/raw/olist_order_reviews_dataset.csv')
df_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [84]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [85]:
print("length of dataframe: ",len(df_reviews))
for column in df_reviews.columns:
    print(f"total unique values in {column}: ",df_reviews[column].nunique())

length of dataframe:  99224
total unique values in review_id:  98410
total unique values in order_id:  98673
total unique values in review_score:  5
total unique values in review_comment_title:  4527
total unique values in review_comment_message:  36159
total unique values in review_creation_date:  636
total unique values in review_answer_timestamp:  98248

In [88]:
df_reviews['review_score'].value_counts(normalize=True)*100

review_score
5    57.776344
4    19.291704
1    11.513344
3     8.242965
2     3.175643
Name: proportion, dtype: float64

In [89]:
review_counts = df_reviews.groupby(['review_id'])['review_id'].count().sort_values()
multi_reviews = review_counts[review_counts.values>1]
print("Multiple reivews with same id: ",len(multi_reviews),100*len(multi_reviews)/len(review_counts),"%")

Multiple reivews with same id:  789 0.8017477898587542 %

In [106]:
#making sure all duplicated reivew_ids are tagged to one unique customer
df_multi = df_reviews[df_reviews['review_id'].isin(list(multi_reviews.index))]
df_multi = df_multi.merge(
    df_orders[['order_id','customer_id']].drop_duplicates().merge(df_customers[['customer_id','customer_unique_id']].drop_duplicates(),
                                                                 on = 'customer_id',how='left'),
    on = 'order_id',how='left'
)
customers_per_multi_review = df_multi.groupby('review_id')['customer_unique_id'].nunique()
customers_per_multi_review.value_counts()

customer_unique_id
1    789
Name: count, dtype: int64

In [107]:
delivered_order_ids = set(df_delivered['order_id'].unique())
reviewed_order_ids = set(df_reviews['order_id'].unique())
mutual_reviewed_order_ids = delivered_order_ids & reviewed_order_ids
print("total orders with reviews: ",len(mutual_reviewed_order_ids),100*len(mutual_reviewed_order_ids)/len(delivered_order_ids),"%")

total orders with reviews:  95832 99.33041729720766 %

In [116]:
items_per_order = df_delivered.groupby('order_id')['product_id'].nunique()
multi_product_orders = items_per_order[items_per_order>1].index
reviwed_multi_product_orders = reviewed_order_ids & set(multi_product_orders)
print("total multi product orders with reivews: ",len(reviwed_multi_product_orders),100*\
      len(reviwed_multi_product_orders)/len(mutual_reviewed_order_ids))

total multi product orders with reivews:  3159 3.2963936889556726

In [117]:
reviwed_multi_product_orders

{'b27251efdb174e33b4c62af317cdc06f',
 '9b1feddaf70fe81f5182faabb45bede6',
 '2318f7d3046fc9a035c165169b54d4b8',
 'f70dff3502fa3fe88532b170cf4f126a',
 'b9374fefc8bd25caac04f6223e7649ab',
 '41d0050b0a103c674289659fdd6f602e',
 '3df55fc07ff463109ce0422439693aee',
 '718657cc80e6e1cd6bb1277c4ced4eab',
 '9201f7a169a49789138b5f56b5190362',
 '9b49c07fc3206cdd7756837757e37538',
 '9903b060ffcaca9244088e1f834fde2e',
 'ebeff2700216eccd71f9e7de886652b3',
 '94faf92860aca2dd583802d6673fd794',
 '3e69c99cf58356667fdbd6b7ab0c1e35',
 '7b1e7ecf29040bd9581a1577a522548d',
 '7731a91dd46b3556ca99d3b3c34373ef',
 '7b97540464c83727a59899b3d604c2d3',
 '9fce4af6a15c3fa67e2ee1b52839d6dc',
 '6e60346a3ee3876c1e4bc89c597ffcb8',
 '0ad0daff42cf44b50d0bac4c64722e4f',
 'bab2b00c7dda561a8e77047d346f36cc',
 'e13c7d85f07a4e00c383115a154dcc39',
 '3040863957c9336e7389512584639bb5',
 '67d760ec323d2c9f0292ec4cdafc676e',
 '6fc8cd5f4cfbea0b694434a10475fd6f',
 'a13562e9c4b0eb8e6ae0946073b213f8',
 'd44913f6177d1b8a369a477ab2823aa2',
 '89ca1c6fae0e21f0395c0e3b1d89914e',
 '4ed127b02fb1ebdaf9a0e4be8ca000f9',
 'c1d3d16d19447e6ae5ea015f6056b3cd',
 'e0e3cde1bd7f993b460771481843727f',
 'c46141b3d5535e4ecaca9ddaf90ba7a7',
 'e15e937a644b742c6083b44d0f9a0ab4',
 'dbcb6cca18be698dc8022a2c700f84c0',
 '5309697895b2dd99b05c248512f668cc',
 '044cd7ffb6a41e6e5513c6595a2893ca',
 '4b6aca1937b0119de6bd8be675067173',
 '33dc68ee07456f6fa5da352d9cca5d93',
 '8af844e18cf7ddedd50343fcd0990863',
 '4ec16f88e884232366f73009df2bf045',
 '748f1a8074500891bf8f786ce3b5c02d',
 'a5beaa646a0becb1965a0f77f1f05934',
 'c5e13c21c49b30c15c64f761f68ed8c2',
 'bb9552306cf6879fde49f4ba3bd94299',
 'a501de32f4f7eba26aaa7864ec8dafb1',
 'f376081d7c5f1767fbc7fae2d19ca32e',
 '2305d46c47c716885a276ec1a322b612',
 'c9fe382a47de702dfad8f4b2ea3d2b3a',
 '589afae8e1396e2a2dc24a1c68223809',
 '4b4badb2df31e851262e8278b3a02871',
 '02d273267575a29864f552b2de598580',
 '2d5fe300d9ae2c54ed035449aac94391',
 '723a7113ee372c5f0ce268c48dfc2c21',
 '1d35b9b8088b6c9e1fcff77fdb44ef53',
 '59bccab4e9193a9229f7d1b73fcb47c3',
 '7905195351d6b5454db9c308ab72288e',
 '8c2b13adf3f377c8f2b06b04321b0925',
 '9e8039eae702d759bca1fe0fcd1209b0',
 'bd335a38abd734d788851cb0b0fb1a48',
 '99bc2347537c9bba890bf1e3939f6f4e',
 'a4cfd47a44ceac0a7ebb64dd03f2a4a6',
 '17999150a37e709ef58ae49a064400fa',
 '84a021f71429800674e0015e862c1b62',
 '64e5cb1dfa641be49d6baa62b8f41b9c',
 '0132451f29a10b66a5cf1bacc85f9afe',
 '31d9a6982f9690f7618f0a5d647504b0',
 '5410087995e1ebb53c26ce8e52ff29e0',
 '672260490e5b2772766e523be71a3a9b',
 '969d4417af042f4e8bb879f49e51b447',
 '9ea386e9542809c5955f1b89354c5e5c',
 '9f0663bf008ccdbfbd96ac9a31ba7442',
 'b99217b1fcf2fdeace7b8d869b76cb91',
 'abccdfc385eeac64f4e5147bc7d9191c',
 'ac3b2d2f26b74c0c5f1e28c2f35abbc8',
 '5f3c3f02ee527647eadaeab108a89f51',
 'fb7b22bb2a29860909a25f91510e4292',
 '6e29fafdff2b42dbeca7ed271dea0fc9',
 'cd9ef363164449df0bf374f87fa1b1de',
 'ba930d713b7bf3dca12e701703ff8eb5',
 '7a35319beabf36472c45cc9ba67f0745',
 '912343626f370ead5ef2e85a9d757e22',
 '6ebb39e4d90eff5c1099de688d9b4f94',
 '35608f7cae2658ba060f4fec29ee1f81',
 'b93bb71b5e2443566763aab6cc80a84f',
 '0ca8999f0176e37f35b6e49a9b2569da',
 '55779fa8fe072d9f8c92d672154558f2',
 'c5bdd8ef3c0ec420232e668302179113',
 'e0138d152658a49efe819e763f0a0cc7',
 'ccf592d5d82b80e4764b14cbfe857be8',
 'b7f4c683de2480a46706baaf3dd167e7',
 '3eb08a4c95b522bed075ec059ad858ab',
 '4b37d81b92f6cc32e5225cec78244917',
 '6e0f64efb04a60cc8a5bff3e30663c02',
 '448645ea240ea7aa0dcc61d2cad9eb5d',
 '6460cc80249f46f8289b2a8d55d61dbd',
 '34933c9ece23c40d4591be765e2b7f27',
 '9846cae21962f6c6e65ad2e77d3c2be7',
 'a6c173f716aac4c915299b74fb4e0b10',
 '39948b49e7e68844f9f5a31d12a3c4c6',
 'f26be57b128ad749636740a15bf6752c',
 'e563afc47cb5fafb2ed8869e9e822e38',
 '7c74884b55b2ef0862e578cc630dfb3d',
 '98f7b0bbb8eebba6398ec18bf1a8cf12',
 'b18dcdf73be66366873cd26c5724d1dc',
 '727f7b96d03192204f43ffb4cc712ca5',
 'bfa80c640c89b8b47f3c864e6de67509',
 '074eb2398def4038d7fc4fb8a5aeb0bf',
 '178dc9ffc66f1968787b253a9318cc29',
 '3735a11cbccd8916dbc9ccf5f671cc2c',
 '74414263bc2db93856b800f04ded2cab',
 '77b062be7c5bd21712905feb8e1cfeed',
 '635d6eda3af27d4cdcee17a82b7aca92',
 '8db8ac0784a54cf5f37a83fdc88fa2fa',
 'cabb660c11fb7f6bbb5f454ea09c0b9f',
 '45193dbb3e96a6b68bcd317c6f840fb5',
 '11f81f5b3445ad54e4c793afe6337986',
 '133b607354fbff7447ce545c8a0fa407',
 '6275a054b07c80fe5b7abe07dda2b366',
 '0758eac62489b47a99c64b7d67c5ff18',
 'a7c0c5a345bb63d37fc8aafab1f86a4d',
 'e9b40dee488f04d79f264cfc3d8a2f0a',
 'b0b822b0f9346fb153a23ab0ac5214ff',
 '6de3383be650cfe96aed26171ad65c47',
 '7e6ae85d806fd4563f0e68f5521321cc',
 '16b6123f7077419424bf89af74e2d054',
 'e151550ba97ec3c6c86f7de205371930',
 '0758015124a0c9af755d31a7bf0efedc',
 'dc30763d1665f5167ab925fbb51202f9',
 '9e22fb4a47d29059ef9689ca8b26d8b3',
 '01144cadcf64b6427f0a6580a3033220',
 'df13cbaf3230c62a4b582317936e8a39',
 'd310bd7091e28dd1dd215b1aae78f9f5',
 '1feae53afbeb20695102145770b6037a',
 '440dd5b80f076b3133c25e668e4df168',
 '961a93eba7486b47946616baaf442372',
 'dbe491c8c7def16cb4b93c51aa88c124',
 '05ebeda0c1aefd787e0ddc914af75039',
 'a824bd4671f3e218495428f200af9bd4',
 'ed2e531820c09c6a5dd68fe295484148',
 '4db2efafa3ef7a9bb740073addef3f85',
 '23822f9bf0e42a3e11bab993f60f84bc',
 'a245a32d07762c385b4620fd16bab160',
 '92636fba2bec02c660ed866c0ab6f4bd',
 'ce3f08db12e92209931e4bff447392df',
 '81a3c1a0ea3b09bad9d4e0a6a3683f4e',
 'ea5b2c0d002d415e1c5e7d7f39c831f5',
 '320dcf288de15e4ff06ebbfce4e42c78',
 '048fec87f5858e3a91ce55d3a944b457',
 'df71ba0f02310921da0a5e4f708916a5',
 '0f20a3721e8997ae2f771ec8cf0c4d3d',
 '6d84eef7bc3b079a4d45a49a3e355784',
 'a9f77c0325604197d9a0048d0dcad33f',
 'b27af682321527a6349f1761eb3f360c',
 'db28a85f64c84ecf4ef58cddcaa1cf50',
 'a18986d0ee0fd3e2c6fe3fdd23ca31ca',
 'ead893b6feb078f2a8f88787db56dcc7',
 '35ba49bc8738a496558fdc62d9303342',
 'c4a4340f8f35d5289ea5eb4dd44815f4',
 'eb22d6eb9946f4e045cffb03414af48a',
 'a5a32befe5eebcc26930e213ffdf3369',
 'a8db6b84057a7a3a8a38968f10853069',
 '4e08bdd0a71b43ba19f8c0a89c8ce665',
 'dffe3c3fdb38dd7ca56eb98408730378',
 'f043d325dd5b6eeba051156b18d49dd8',
 '75156818c2863d3be5ab7b08e728e43d',
 '8738785542fcbf848621d353326ec75d',
 'd08bba6d656adbdc54eaf30b29532e89',
 'd2e280e54ecb98f30a641bb661336baa',
 'ece8853f47b1069c213415c8b64ad6b3',
 'cdbd8e67ad713458b75e3543d685f456',
 'e50118751e7505e22fb6491d648be823',
 'eb71a8bb87819d656f272861f49e3477',
 '08c7ad853a45735072fee2be62052da3',
 '589eac637e68da58add10ee5e6710bac',
 '87440e08790d85796f5b8bc9f5ed2707',
 'a738e9e6770c9eac21287cc96d82dc76',
 '9914efa57f1a52e1c0a2735c0f927bbf',
 '171c622bc5e64b427c2708aac335fe6c',
 'a85429530fd3281381e34d128b357d91',
 'd4a72eff3bfdb6ff7667bef4119283e9',
 '6b51309cb191abb919de57f626c06719',
 'e37cb83a77f2c53e5710ace789c66a97',
 '3de9534894fc4afb4a93086499626223',
 'cd9cbb9b4a02d47f00a71acb290605a6',
 '2850436e0937a8f3408d9b9929a455dc',
 '334e118f51cc0e200822d5f117db5f19',
 'd15975c69a074c65aecad997cbc6b748',
 '4bb3eed0b423bcae4c063a401e17308e',
 '2609c6729fdff11b1686733d0852c7ed',
 'b2904e4b8dc7f4317993cb7d645f1a85',
 '46081612169925ef8882b3bbf1c5011d',
 '9e6bc602a2466daa94736f31d1319c5d',
 'ac9394e6566c5245be91e3dd87c8d5e9',
 '60d10864996df64e9b7789d51ba03da9',
 '83a748270a134df5ad432092f4e26e4d',
 'e85a5feeff7fbda800ceecfd2fb221e1',
 'a445af0d83713885b6b576796191b1fa',
 'f52a5a508f96400a02ab7d6dd3d73146',
 '771c4f1f521f462e4b95619e648aaeab',
 '153a0c506e50c26d2279e2ba4187f892',
 '0f9a932982d1a4ee6f2b4d9a874a5fd0',
 'ac3c62295b2d88214642ed7f7114d468',
 '5528a3c9850e07ac5eeea39f275d6c5e',
 '161743a94abde3599def5bdce166684c',
 '173cd9df6006351e8e5151ea0f400bd3',
 '42d0d6be3900c1f50190096f216695b1',
 'cb78dafa7c2ca5d9eafdc6f02cd4f3b7',
 '6a93b0cb6a5a2c7732677334a4535a1d',
 'fd74a95ccfea489d33e78d0c076a640f',
 'f55550ceb7e4387a3fc606d19e6461b5',
 '3c1ceafa085d9c28c784b0ad99895a6e',
 'd0f04dee9c829112fe7fa0842b4b0a8a',
 'ab116cd2cf14c6bfe1c624dfaedce308',
 '7d8f5bfd5aff648220374a2df62e84d5',
 '1f3be0325231ba927e78b6b517db7455',
 '67c03c278fad216ed9ab5573e8cc551e',
 'd33982acfe99b8e0b0383c2ce8ae19bf',
 '732cc391e9ed0eb247bc25c02a19af0e',
 '09224348db675e0c2a00ebe2bd9599db',
 '8087ec71e393d4dc6fc48041fe63cd51',
 'b70c2a4797319570dbecddc366fb25c0',
 'ffc16cecff8dc037f60458f28d1c1ba5',
 'becf90dbbea6e1a229814dab50912be4',
 '778d6f8f92b218606a82dc5d2f5221e2',
 '1e1bb536916a9964978ee59e6d6d0cca',
 '3ac0f5a50ede5981b44f30306bb853fb',
 '2c039eca196d1a548fd739e82713a1b1',
 '8c0921d37402722b282083329db79f9b',
 '5e305bce2589552e505f2db43aaef669',
 'aaa6f66c3f76dbaecfc60183d6a248ed',
 'd2d7d1df7a27b9c2249fdbac70ef9fa6',
 '21a5a6a3ba44669b781dde94b19a361a',
 'e061acbc3114d57440a7250db18b4e0a',
 '9b8aaa74d468897a211fb359950937e5',
 'da2b5ed33ae5068005e9d2c43e7a3de1',
 'ac2dcc9201c601c1030aa6daa7337f95',
 '0e69198c87f4da026d7daf96d91b194d',
 '1a45c130db33df3cb0e3cd16f0a8ae9d',
 'accde1ef3208fde380a66c1706494ba4',
 'be4ce210f993d9e26a013ae7e93b6893',
 '49cafbbff42233d698ba0e203810e394',
 '344d7792475d51c5c3b9d41758ef8f44',
 '6816ae2fd8e9a4a6674dc2eb053da35b',
 '8304cd42545c641d13b9165c7028c85a',
 '6f22dfc6908427b839369dd36662e575',
 'cf5dc40ae925414c07d1a74645ced6c2',
 'a8998c981964bf8bac216e296e00b309',
 'a3cc993782ea3572fbd27048f12712ca',
 'd82845f8b7ebd4d9b7ebae995e0ff08b',
 '6b325b9f635e80a6be4eaa131ae6141a',
 'bb82809ea3ca9f3edbe589b60e14e0cb',
 'db4d1cf54509ad6f47b9e8b09d2a2c40',
 '66c14b06bc8003888862ecf57985bbaf',
 'c297e25bd82cc7de06d7cb843e1c599f',
 '69eab1df0881c314c60f8a3a1935cfcd',
 '95e418ea130a24742051eb864d986af5',
 '8f82857f5a738c96bb40a551c4c0bb40',
 'cb1ba18d16a7bfa79c87de73dbfc46db',
 '64766c48d0be21c815096ba7bac96ed5',
 '8f2c3eb88f3127cf27574d29f0c58ef9',
 '0807b732c1e7621078473cec87389c8d',
 'f0a795dac0e5cf6a6f98cdcab173ffb8',
 '2d070e3a721ccc7ea881f090802680ea',
 '095f058cc1daeb1e7ba1c133473090a3',
 'ffa5e4c604dea4f0a59d19cc2322ac19',
 '1b7efcda93ef629e74df8b1fcd2b1f92',
 'da737ef3ec9b9835b98345f6c155cdef',
 'd65f26752fd6834bfb0a567b581dde3b',
 '95f3615ae63fefb578bbcb55f66fba96',
 '8c552a81cd185f54e557a0c955602a75',
 '2edcf6adbf3719366560d6863cb28799',
 'b0ff8e6a9bb47b224a599ff0c161006b',
 '804a79d234b0f9470b218e9abef45e7e',
 'f396e1280028fa9c8c83111abee5f2e9',
 '0c3e2dc4a3eeb282bd4df0b620dcff6d',
 '1f50915cd289eb7e0a0da3f4300b92bc',
 '28c723236c59abdde8cca758e1afd07a',
 'a162843206c281a243d96c3040e7e08a',
 '4412d97cb2093633afa85f11db46316c',
 '20cc317e80d8a478c61b30c26edd3f0b',
 '0343fa2096b6d04743321f9b9f62c1e0',
 '96a37e69d0e47674bb4214448cf76dc8',
 '45390ff93f092f0de1524d486a172c33',
 '59da3bd70f1d9278c6ae1577cd16de12',
 '36bed4b6f0c3a5086108ff51d0afa4dc',
 'ff00a56fe9475a175cd651d77c707a09',
 'c05cb9c2c6907494337ded1d059cbc7d',
 '668ca58f384c0f1007054dbf6c280242',
 '8adafb3466daa5395694d3a906ff9d40',
 '112b993827414a482ef6534e251fad3a',
 '73e0f16a25c4d33221c6032d3bdb2680',
 '0a32aa7d8d3f344fb31eac306336daac',
 '6653526158fc41798fd489f9b3c86b56',
 'ae8b5df90eaf220f63f5ed4865cd222c',
 '1181af08903c7e8cc1cd6cd5df586dd6',
 'd54668cf2e710089072d269f793d589b',
 'c7387d86e09f2823f6062d8c2378ce02',
 '26693e638808e1e5a1b09eaa16a1fde8',
 '483ff5a41552b4071ff9d8bef07c6ee7',
 '168cd953540aa3251bdfb407cdc4b6d4',
 '41932b54e17f6ae1f4be1f8886f47883',
 '34c1a691fc965ffffd792dbd8e7ac087',
 '6ca4871d007ce3c4a6173f53028c28fb',
 'a889c83e9d58375bd1747f31daa8ad8d',
 'f37977715eac869c24d6402da2b7a3ac',
 '98d62868252c18a0fde796ab89c6e08d',
 '0540bf9189ef17aab470c4942f760e78',
 'f04bfdbef5359607d39e66fccc9cc0de',
 'f9f88b0c2d64a8b36cbf24b1b35cd3d9',
 '9d302458a5c2070516051da353068870',
 '2c293bd3c9f41735731112a36cbcaf81',
 'ad0d46c22c5a9dd2699f5142b1882f5f',
 'b9b288cdc42a600d0a460dcb92865e4e',
 '64ccc97757023bd10bf48bed7f1e14e3',
 '688052146432ef8253587b930b01a06d',
 'e126a4c926bda89ae444a788cb74d989',
 'f7ba0ab952e0165fed5ffae1ffff6627',
 '84c8e85801737b1626fa898ede7682b0',
 'f31cf521d461f5b8b5b1456a0448495e',
 '684497197738631cbe11c77e531a3220',
 'b8cf03f4a08e3dc7eb2509ef520b20e2',
 'dc20ddee58064808944cd819f518dcc1',
 '22aa0b4e8c7855fd8d534a7692579a36',
 'fe2893f4e6b71e79a7aec9c777744a16',
 '53892f0dd25da0289fbdb0053853bc34',
 'acce194856392f074dbf9dada14d8d82',
 '45060534aef780077c10103b60fe71c4',
 '596f9f1543a2c306f3aec8f22e806ff0',
 'f0b3358d0acb067d9c09d3fb376a5e0d',
 'f60ce04ff8060152c83c7c97e246d6a8',
 'c2c7eaa5d10a2d1abe8f0948534ef196',
 '74da1d033cecf62865d267673aeec395',
 'f2e689a11a0a962aa271e7715b516ee2',
 'f71e43a268bbabaa7736af38f0c02710',
 '2baf80a0f30b1660ef1d0653314c04dd',
 'a0ad7865ea22bbaa2f026e3aee583484',
 'b335c1b6b81809fb3de72bab88595134',
 '46f294819f56193f9e3566a3cc3ac123',
 '2ce3c61f3add382691fcad6a04f52680',
 'a219a9f28e900359410d7cb6329cdf39',
 '8669133949d3dda2b99bec214c2c299f',
 'c629fd3aa69824b58230aee97ab8930d',
 'e68452f95dc9b23ff16c3ed8ca0275ac',
 '307691e9d5567f71a6ad5945a34170f7',
 'f8a7f99695460acdbb89605f807bc78c',
 '5d74b3ad92a846bb883841ab6a20d629',
 '07420892c4caddea9908f3e55218a5ba',
 'db7374d1f9c8965e0fbbc1fd1cc916fe',
 'f2f276797fe0c5bb220e8fceefd0220b',
 '28f3f76a069124ea37b2e0c43408ae47',
 '3b2285d4d80f742f34cc959e041722a9',
 '79f04f286db371d16fa7bb23b3ca8b5f',
 '98ffbd84c7dcfaca87f6a248719b9bb7',
 'cf1a41ef29ec5a9935e2d1809af97312',
 'e75011be2ec3dec23d2ed6757d35c792',
 '3990f96693d321ac142fff312bf3706a',
 'bc3ac768a8963f4ca68942ea6558fc9f',
 'eddaccd03acbce06c3db36e1b9f8cd4b',
 'e48050e10ceca27e33d705b4f1adf5c3',
 '2eb868f2f7abdf4284337d1cdeb7399b',
 'b9a089706e16d5490f7a2feb363e32e9',
 '1852f4003a3be7d9054403de86fc4280',
 '4060a8c4cf4cdd2f9ffd6f7af3930fde',
 'aa2dc936dd126536c8f2eb4dbaf37333',
 'a43f64ef96ea58be757bb2afccfd0e4f',
 'c33847415203d145000463a6976952b6',
 '2153e9009ecf443d84e5f48861fb7094',
 'd419b374d8c1d6ee8ef676b3d5483193',
 'a7f50550b7c9925554fb9bda2d7d220a',
 '005d9a5423d47281ac463a968b3936fb',
 '491c5fb7589518eeceb842216e1b4441',
 '72705672ab6238e6354d9889c34ec409',
 '8c78d01de3a9009e23d6877a7cc9be20',
 '989d4dc670329cd432f4345b25194cb9',
 '9dfd36609f9bcc11f7712d98466d9aa5',
 'a2d65cbc20a4d7cbdbda0bc41b1e228c',
 '20082947b2fb23b28d05f616b985cdab',
 'f5eb5acec9783ed29ec9e62f521e409e',
 'e337cdc735f7a8764df34f678640c7dd',
 '483ad8e78dc16136316aded1f0602031',
 '168bda17add369de7d250129f41c6fb2',
 '8de1aae5083a3fd8914d84cfcf07dbbd',
 '0a6941f89f53dc1f622f877b23601ed7',
 'd57eab70175d8611d6a811d6c2af63ae',
 'b91d854aba08883a55d43af8856e90d8',
 '879a1b657dd0ac822411797d57cfe29f',
 '441596a9fde121f33c360d9c9ecae437',
 '533ca098906e55ed14be6385223b86d1',
 'be7f750bcb350e7e289e828efc763466',
 'b33ba27bcc778a34f2d46f4138302b14',
 '5e38951c465ac4f3d14da15694710a74',
 'feded510efe2a76dd134d8533af626f9',
 '9edba4db56f4797983bd410419163414',
 'e9ceeecaa2923bd7ba1ffa607fb0f9fe',
 '443f3ab34f06d2d9124cd153812b4ba6',
 '8d8a1fb20cc3bcbed0c51fd0c70bc538',
 '27890ab4f1e69e4ada365fda76df26df',
 'c859bbfda403ac31857038177a367e1b',
 '4620d9ef6b668ab50248cec23ba52f89',
 '5fec03fce725fff481779aff4be805d8',
 '508d8fa044fdaa4d8faff57a4e72e64a',
 'c19f01711a28636df6bb57d440865c76',
 'e2a34138116519cb702c72c12aeb99fc',
 'c4d1c7a8479672cfedc8850e5ab6f3c8',
 '0a77b770428bccbea7f9dbf8aec5d6ae',
 '4bdb3af7b8d5db206e5ea7b4f964ba4c',
 '55a90b35362150673d3546509274be53',
 '3e4a2b96719ecae342e5d413e97a1be2',
 '64c62ba0c1c347994fbc56da00ce2dae',
 'a24474d0a4ebace563a0695a14b5bb0a',
 '9c9519dbd0554cfc5c787fdc7fa8ff42',
 '0a9fc736e210f495e2023d3a9e10319a',
 '316689f43f1ba849c8cb83df6f355632',
 '97c1ad9812910864f063fcc01544976b',
 '9298c4a7ed6bd4d2cc8433f7e4053fe5',
 '829f21ada22c20b2a15c75f8b63a0533',
 '335a2e98058fdc2ff97c02856d53a76e',
 'a08337c882ce2f3733377bc48c5ca3ae',
 'c2320c404179d2b8805c42b8b8de9668',
 'b9ba0d763542807cc21f8fcd54d80f6b',
 '8e6c25f5e4548a8a880c0339b15b8ab7',
 '017dcb6892d4469a13dee34f241f8c4e',
 '924d7c4505c90dd9c3a4ab2c3c5daa15',
 '48568f2508e7bb655a607258e5b7a941',
 '6e5fe7366a2e1bfbf3257dba0af1267f',
 'a849c2a7ea93e09f56fba22f019394da',
 'd889189b765c3c0257ebfbb1ddc34770',
 '4087849bcc671e4fd0e10770daa7bff2',
 '1683815c34e20076a6b3a8b1fd3d8809',
 '5718be47d367f91087182c0b796f77fb',
 '44367541b21451fc1fff30873b2cd899',
 '97b91c745aa3a478f4e00df4c15069e6',
 'b798fc527c548bfa5f069b5b29195275',
 '94efce41dfeea273248d6b60b98fdf71',
 '023669233121f0fb7899e5be2b22885f',
 'b44e4934b1e5508c95af97751e9cfd6e',
 'f926f5a21b7bab3b81bffa528bcb1ea3',
 '9769f28d910e7304d7bf0fcd32d8ecd6',
 '431f71d848d8dc0ee88bdd5ab9697865',
 'b785c9a36593879a9109ad7539f2467c',
 'f2a871697115fe3d0619068a8f8eec25',
 '3e22c141d2861860889375c6fd7b89b3',
 '3a242772733bbe85f793b47f375aaed4',
 '4962c62f110070284d4a13fbc3a2c970',
 '427b93d447dc29957700648673d6256f',
 'ffb18bf111fa70edf316eb0390427986',
 'c51ed3d77baf76974358a156521bbd16',
 '9bcae940b24680a6ca263ec7ffb30ccb',
 'db840ba7f7a60faf5eff58723492dfe1',
 '62ce4e3989a3477928510bb4d1064cc4',
 '39010dbe92bbbfaf08e8d13f7c9bb118',
 '9ebfcd2bc9b6535e4bd2f4a199ccb665',
 'e35bd284b205ea082108ae3703c84428',
 '3c314f50bc654f3c4e317b055681dff9',
 'f1b0d64e31c26320c0447cd14d66f4bf',
 '66c251b81283a4147f2ba97851126741',
 'ee9f6e9060450329e05aef3781e5ed38',
 'd9715bd8635503e2e6bf01a078df8c10',
 'b03614607ed7a36258b150150b1e898b',
 '189e75e25de4939a240746314c77f656',
 '5aa89bb7eb1a8dca4d70fcd37878c8a4',
 'd7ae3c10c3a4c7a721e64ba401ee745b',
 '1dedb63df54bd6377bc3e2b61ec4c791',
 '687fae09ac6fa7c5e99990afb9ddea3d',
 '8a0c45c3a220380c7e82eb944150e5e1',
 '0cda834be88c6e549a9895efe5e0b49f',
 'cef4e03348c70c1c8eee3647083675ab',
 '751161aadc4b3f4e09ace1f4ea2c146a',
 '79d99d8498728081a42a978071007d45',
 'b8ed89bd3f1fe72244f0f616acdc7da1',
 'e6ed38386107802a72ec8197195f79a7',
 '3fb5cb07abb84703f0890f6c92589bb8',
 '71690141b0ebadd9464cd3adb5c6b881',
 'e98077a0d199a25a40eab3b14cc230d4',
 '0c57cbfd927d9e62af8beee6d48920b7',
 '67ba689f4426cad886c40eaf487258b1',
 '7e40398e4b930885edc608594647816d',
 '6a2979d48eda14bfbe2d632638ae16a2',
 '9797fc9d23d5187db0924184bc5cca44',
 'f11b670018cde48868c96b03c4d3d1ce',
 'ee85f19387464b0c9f70dfb6f5005a18',
 '22dd3a753c65e7fcfd78f61a4ad7b32e',
 '9aec4e1ae90b23c7bf2d2b3bfafbd943',
 '8d9341adb50a81fee7dd3480e9f34c2a',
 '3cb2ba0f933044d545dcce9bb8dbbed8',
 '3a272f742a03e6f800cdc955ef4c173e',
 '51d70226d271148b34f0ae2a6aaef7e8',
 '299a083b6bd82294402dfa7d0df9980c',
 'eda1c58c902319868f5053e8fda15c2e',
 '9d4837e9f15d4e57e4783e22786cb407',
 '32b719ae1cbb8bd2e7a59704cdd4146f',
 'bff9bf477ce043ff4e51e929fece6d55',
 '72e57d0b326731ddd25d0d44212a42cb',
 '190a104710f7a653bd65f673e8f5ba11',
 '5f3ce710839dcf62389d5187ece2d4e8',
 '1330176f6500125ff6e8e10922fb714c',
 '6616fa4c89b8bf2a7e17271cdc542fca',
 'd61fb054800247ebeef5200e8bf9c9bd',
 '5a45e21be984a22a54a63a7e950c2f0e',
 'ccbf44556216d2ad81b039514a0d8877',
 '25de47610b1fe93d066d999828c0fe57',
 '804f733828d8587c734a1d8fc5634e06',
 'c3ad507aba1f6b47354085e7e6bed0cf',
 '4a2e9754d61d7f8f0b41fec143e166e4',
 '3cd4d6461c966c84e6547503dc04df2a',
 '2458754d32649761e2c31fd65cb3fdf7',
 'b16a844a8a1b4998e1505f65a65d1e6a',
 '5c4e6dc9331f62136e1d51c2af608af9',
 '44afcef35a5f8874ce556826e49769a8',
 'f0635a71f7207aab8ef29df0d1ee7104',
 '291cc6d48f9475a822aecd9c9a78d4ac',
 '42da631a2f5302608f86e8cee55b8d40',
 '531a74ff9a6617b0cae88c4b67646988',
 'd18a9528e8077026b951849741ab227b',
 'fe6c4a42298295647106b42549a98eea',
 'e56f72c9203fe285a42e1c21888e44d1',
 '8b9ac5a8d0bb9e3350171b0a7e89cc5e',
 '168d3552147af1da6282c46975968c45',
 '214a42323dd7ec45504d319315a1386b',
 '94af94e55976f5fdd5048f5166123639',
 '61685f5d646af5b5f7fbba31e885c7ec',
 '357769c200aa5a3a9b859db2f47b9b65',
 '81c75e6fe26085262f147cf6a6c0d367',
 '862cca64868df4c3a3f0058a93aef465',
 'c5aea2f23df89cdf58e3c3721456f0b0',
 '4f83719808124739d1936b272a2a3750',
 '4964b712511de5c351d07b12d57e5cc7',
 '4dea917f3fa605c7d6eff1a97a207768',
 'fe755232f249d0844951831268c55593',
 '368b20312c68710e9d75cbb5cef5c469',
 '6e82dcfb5eada6283dba34f164e636f5',
 'a436479c10d07646de88aac101c689df',
 '353452698ed9b7e594c057af6d63c95f',
 '7a8642ee90484b296acc07b910c2c44d',
 '892d14cfe4157476879d57275df6615f',
 '2804019a383c2bf8db7dde416cf663d2',
 'd839ea07a528e914f89702508023da37',
 'ad1c31ec035e55a4187e536234b28e38',
 'f176421e9956528da385eb686f70b7c1',
 'd35588da5ba45ef8d7b51fa96db86059',

In [120]:
df_reviews[df_reviews['order_id'].isin(reviwed_multi_product_orders)]['order_'].value_counts(normalize=True)

review_id                         order_id                          review_score  review_comment_title      review_comment_message                                                                                                                                                                               review_creation_date  review_answer_timestamp
0054fba4a2c8ddef00af2a4805eec53d  b07ccdfa28017f65163b05eaa308ff97  1             Falta de produto          Comprei duas cortinas porém só veio uma cortina na nota consta duas gostaria de saber o que vai ser feito porque isso é falta de respeito com o consumidor que compra e quer recebe aguardo retorno  2018-06-14 00:00:00   2018-06-14 21:03:41        0.002299
012902a4690846e0d3e1cb3a950a1bd0  cc9760bf7b5d5b74c4d1eb1ab6405b50  1             Produto ainda não chegou  Recebi um pacote com apenas um item do que comprei, estou com o recibo. O outro item não foi enviado e não consigo uma resposta do vendedor                                                          2018-07-24 00:00:00   2018-08-16 15:39:00        0.002299
01d08cbdbce127b0a4ed6c60e1ee6ee1  6727a4e9eed7135cefc6d0f9de7f88a3  5             Recomendo                 Recebi dentro do prazo estabelecido, adorei os produtos                                                                                                                                              2018-08-02 00:00:00   2018-08-04 09:40:05        0.002299
02f1ac2848069e79cff5433e9a149d55  c1ff65479834ffeb424c5a78cd65ce4c  5             Produto lindo!            Super recomendo! Lindas as luminárias e entrega rápida, antes do prazo.                                                                                                                              2018-05-11 00:00:00   2018-05-14 13:44:51        0.002299
036963bd2c4b9a231d2a7079bbba47a8  56c342adb8f074b20da098539a429d68  1             ruim                      nao recebi o relogio de parede                                                                                                                                                                       2018-08-14 00:00:00   2018-08-14 21:58:24        0.002299
                                                                                                                                                                                                                                                                                                                                                                    ...
fda44869178ded7ac2f6804d40980075  4d680edbaa7d3d9bed69532957368a03  1             Pedido não entregue       Se não me derem uma posição quanto o meu pedido não entregue terei que tomar minhas providências na justica para sanar meu problema.                                                                 2018-08-28 00:00:00   2018-08-30 11:07:07        0.002299
fdc2ee0da2fafb0d0b54fba02d3e7ac9  669d4be1c2a2cab7e5ec040bf54c5d91  1             Não recomendo             Comprei 3 produtos dessa loja e só recebi um. Sendo que não tenho nem como rastrear onde foi parar meus 2 produtos porque colocaram que eu recebi. Vou ter que entrar na justiça por danos           2018-04-27 00:00:00   2018-05-18 15:30:15        0.002299
fe1c8ee14123592e8b7e9f391b7ac4bd  0c82a229fc22597c2361656cba8d3230  5             Super recomendo           òtimo                                                                                                                                                                                                2018-05-22 00:00:00   2018-05-28 18:32:54        0.002299
fe56e99b5ffba585991af5315e731935  5658e0c28f9e67db30ba9ec22888600e  5             Ótimo                     Produto veio corretamente, em um prazo muito rápido. Indico mil vezes!                                                                                                                               2018-06-13 00:00:00   2018-06-15 09:49:04        0.002299
ff2e013fc115e2c9d5d21874e673d1d6  984b33682c48ca8bfd773ebdfd0161fe  2             Item nao entregue         Consta na NF 2 itens orem apenas 1 foi entregue. Ja solicitei informaçao sobre o item faltante.                                                                                                      2018-07-14 00:00:00   2018-07-14 15:31:52        0.002299
Name: proportion, Length: 435, dtype: float64